// Dockerization


services:
  mongodb:
    image: mongo:6.0
    container_name: ecommerce_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ecommerce_chatbot
    volumes:
      - mongodb_data:/data/db
      - ./backend/data:/data/import
    networks:
      - chatbot-network

  backend:
    build: ./backend
    container_name: ecommerce_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/ecommerce_chatbot
      - GROQ_API_KEY=${GROQ_API_KEY}
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - chatbot-network

  frontend:
    build: ./frontend
    container_name: ecommerce_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    depends_on:
      - backend
    networks:
      - chatbot-network

volumes:
  mongodb_data:

networks:
  chatbot-network:
    driver: bridge